version: "3"

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
    command: >
      sh -c "python manage.py wait_for_db && 
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=backend
      - DB_USER=${DB_USERNAME}
      - DB_PASS=${DB_PASSWORD}
      - GOOGLE_API_KEY=${google_api_key}
      - YELP_API_KEY=${yelp_api_key}
    depends_on:
      - db

  db:
    image: postgres:10-alpine
    environment:
    - POSTGRES_DB=backend
    - POSTGRES_USERNAME=${DB_USERNAME}
    - POSTGRES_PASSWORD=${DB_PASSWORD}