version: "3"

services:
  app:
    build: ./backend
    volumes:
      - ./backend:/backend
    expose:
      - "8000"
    command: gunicorn app.wsgi -b 0.0.0.0:8000
    depends_on:
      - postgres

  postgres:
    build: ./postgres
    restart: unless-stopped
    expose:
        - "5432"
    environment:   # will be used by the init script
        LC_ALL: C.UTF-8
        POSTGRES_USER: devopspy
        POSTGRES_PASSWORD: devopspy
        POSTGRES_DB: devopspy
    volumes:
        - pgdata:/var/lib/postgresql/data/  # persist container's db data to local pgdata/ (mounted)
  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "8000:80"
    links:
      - app
volumes:
  pgdata: