# Generated by Django 2.1.8 on 2019-04-20 17:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_reminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='time',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
